apiVersion: velero.io/v1
kind: Backup
metadata:
  name: cassandra
  labels:
    velero.io/storage-location: default
  namespace: velero
spec:
  hooks: {}
  includedNamespaces:
    - cassandra-stateful
  storageLocation: default
  ttl: 720h0m0s